/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 08 14:40:54 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CalculadoraSimples_ESTest extends CalculadoraSimples_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("/,F!Dl<Jb9)Qh:b");
      SystemInUtil.addInputLine("-4");
      SystemInUtil.addInputLine("-4");
      String[] stringArray0 = new String[10];
      CalculadoraSimples.main(stringArray0);
      assertEquals(10, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine("/,P!Dl<Jb@9)Ql:b");
      SystemInUtil.addInputLine("6 0");
      String[] stringArray0 = new String[12];
      CalculadoraSimples.main(stringArray0);
      assertEquals(12, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SystemInUtil.addInputLine("*me!-* 7");
      SystemInUtil.addInputLine("1");
      String[] stringArray0 = new String[1];
      CalculadoraSimples.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SystemInUtil.addInputLine("-----------------------");
      SystemInUtil.addInputLine("0");
      SystemInUtil.addInputLine("0");
      String[] stringArray0 = new String[14];
      CalculadoraSimples.main(stringArray0);
      assertEquals(14, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[6];
      // Undeclared exception!
      try { 
        CalculadoraSimples.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("aXAgS Q1]T(<#");
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        CalculadoraSimples.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      String[] stringArray0 = new String[8];
      CalculadoraSimples.main(stringArray0);
      assertEquals(8, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("/,F!Dl<Jb9)Qh:b");
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("1");
      String[] stringArray0 = new String[10];
      CalculadoraSimples.main(stringArray0);
      assertEquals(10, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SystemInUtil.addInputLine(".3HI.:DUiog%h");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      String[] stringArray0 = new String[4];
      CalculadoraSimples.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SystemInUtil.addInputLine("---------------H------");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      String[] stringArray0 = new String[9];
      CalculadoraSimples.main(stringArray0);
      assertEquals(9, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SystemInUtil.addInputLine(" ,P!0l<Jb@9):b");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      String[] stringArray0 = new String[5];
      CalculadoraSimples.main(stringArray0);
      assertEquals(5, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SystemInUtil.addInputLine("+Y'Bssnr7%");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      String[] stringArray0 = new String[4];
      CalculadoraSimples.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SystemInUtil.addInputLine("*:Z`?P7s0R");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      String[] stringArray0 = new String[4];
      CalculadoraSimples.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CalculadoraSimples calculadoraSimples0 = new CalculadoraSimples();
  }
}
